name: CI on testing + push images

on:
  push:
    branches: [ "testing" ]

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  AZURE_RG: ${{ secrets.AZURE_RG }}
  AZURE_REGION: ${{ secrets.AZURE_REGION }}

jobs:
  test_build_push:
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGPORT: "5432"
      PGUSER: postgres
      PGPASSWORD: postgres
      PRODUCTS_DB: products
      ORDERS_DB: orders
      CUSTOMERS_DB: customers
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres readiness
        run: |
          for i in {1..30}; do
            PGPASSWORD=$PGPASSWORD psql -h $PGHOST -U $PGUSER -p $PGPORT -c "SELECT 1" && break
            echo "waiting for postgres..."
            sleep 2
          done

      - name: Create test databases
        run: |
          for db in $PRODUCTS_DB $ORDERS_DB $CUSTOMERS_DB; do
            PGPASSWORD=$PGPASSWORD psql -h $PGHOST -U $PGUSER -p $PGPORT -tc "SELECT 1 FROM pg_database WHERE datname='${db}'" | grep -q 1 || \
              PGPASSWORD=$PGPASSWORD psql -h $PGHOST -U $PGUSER -p $PGPORT -c "CREATE DATABASE ${db};"
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & run tests (product)
        working-directory: backend/product_service
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/products
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest psycopg2-binary
          pytest -q

      - name: Install deps & run tests (order)
        working-directory: backend/order_service
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/orders
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest psycopg2-binary
          pytest -q

      - name: Install deps & run tests (customer)
        working-directory: backend/customer_service
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/customers
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest psycopg2-binary
          pytest -q

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: |
          az acr login -n $ACR_NAME

      - name: Build & push images to ACR
        run: |
          LOGIN_SERVER=$(az acr show -n "$ACR_NAME" --query loginServer -o tsv)

          docker build -t ${LOGIN_SERVER}/product-service:testing ./backend/product_service
          docker push ${LOGIN_SERVER}/product-service:testing

          docker build -t ${LOGIN_SERVER}/order-service:testing ./backend/order_service
          docker push ${LOGIN_SERVER}/order-service:testing

          docker build -t ${LOGIN_SERVER}/customer-service:testing ./backend/customer_service
          docker push ${LOGIN_SERVER}/customer-service:testing

          docker build -t ${LOGIN_SERVER}/frontend:testing ./frontend
          docker push ${LOGIN_SERVER}/frontend:testing
